project_id = "vhxxcthhugsrezigxvxh"

[functions.ai-assistant]
verify_jwt = false

[functions.create-coach]
verify_jwt = false

[functions.sales-webhook]
verify_jwt = false

[functions.track]
verify_jwt = false

[functions.process-content]
verify_jwt = true
